version: '2'
services:
    bitcoin-app:
        image: bitcoin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bitcoin-mysql:3306/bitcoin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bitcoin-elasticsearch:9300
        ports:
            - 8080:8080
    bitcoin-mysql:
        extends:
            file: mysql.yml
            service: bitcoin-mysql
    bitcoin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bitcoin-elasticsearch
